name: Deploy my app

on:
    workflow_dispatch:

jobs:
    DeployApp:
        name: DeployApp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: deploy-app
              id: DeployApp
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  echo "**** Setting up aws access."
                  aws eks update-kubeconfig --name my-eks-cluster --region us-east-2
                  kubectl get pods -A
