name: Deploy my app

on:
    workflow_dispatch:

jobs:
    DeployApp:
        name: DeployApp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: deploy-app
              id: DeployApp
              run: |
                  echo "**** Setting up aws access."
                  aws sts get-caller-identity
