name: Deploy my app

on:
    workflow_dispatch:

jobs:
    DeployApp:
        name: DeployApp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: deploy-app
              id: DeployApp
              run: |
                  echo "**** Setting up aws access."
                  export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
                  export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws sts get-caller-identity
